version: '2'

services:
    nginx:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - .:/var/www/thefinchmeister
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf # TODO put in dockerfile
    php:
        build:
            dockerfile: ./docker/php/Dockerfile
            context: ./
        volumes:
            - .:/var/www/thefinchmeister
            - ./docker/php/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf # TODO put in dockerfile
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: thefinchmeister
            POSTGRES_USER: thefinchmeister
            POSTGRES_DB: thefinchmeister
    node:
        build:
            dockerfile: ./docker/node/Dockerfile
            context: ./
        environment:
            - NODE_ENV=development # Affects which yarn packages are installed
        volumes:
            - ./:/var/www/thefinchmeister
        expose:
            - "8082"
        tty: true